# Generated by Django 3.0.1 on 2020-01-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_link_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='firstChar',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
