# Generated by Django 3.0.1 on 2020-01-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_link_firstchar'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='fileSize',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
