# Generated by Django 3.0.1 on 2020-01-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_link_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='VT_md5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='VT_msg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='VT_permallink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='VT_resource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='VT_responseCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='VT_scanId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='VT_sha1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='VT_sha256',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
