# Generated by Django 3.0.1 on 2020-05-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_link_jsonfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='VTFile',
            field=models.FileField(blank=True, null=True, upload_to='VirusTotal'),
        ),
        migrations.AddField(
            model_name='link',
            name='certFile',
            field=models.FileField(blank=True, null=True, upload_to='Certificate'),
        ),
        migrations.AlterField(
            model_name='link',
            name='jsonFile',
            field=models.FileField(blank=True, null=True, upload_to='Static'),
        ),
    ]
