# Generated by Django 3.0.1 on 2020-08-14 02:48

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_link_privacytext'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='smaliList',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, max_length=2500, null=True, size=30),
        ),
    ]
