# Generated by Django 3.0.1 on 2020-08-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_link_smalilist'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='privacylink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
