# Generated by Django 3.0.1 on 2020-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='TrackingURLSFile',
            field=models.FileField(blank=True, null=True, upload_to='VirusTotal'),
        ),
        migrations.AddField(
            model_name='link',
            name='URLSFile',
            field=models.FileField(blank=True, null=True, upload_to='URLS'),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='APK_List'),
        ),
    ]
