# Generated by Django 3.0.1 on 2020-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0012_auto_20201009_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='sha256',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='TrackingURLSFile',
            field=models.FileField(blank=True, null=True, upload_to='Tracking_URLS'),
        ),
    ]
